### ISSUE TITLE
result is nan

### ISSUE THREAD

**Issue by zfxxfeng** [tsc2017/Frechet-Inception-Distance#1]
I try to calculate FID of to batch image,and the results is nan.I try many times but it always is nan.Can you help me? Thanks so much!

**Comment by tsc2017** [comment]
Hi, I don't know what your code is like, but I guess it is because your sample size is smaller than the `BATCH_SIZE` variable. If this is the case, it is suggested that you use much larger samples (e.g., 50,000 images from each distribution), as you will have estimators of the means and covariances with lower variances.

**Comment by zfxxfeng** [comment]
It works，Thanks！
