### ISSUE TITLE
calculate for mnist dataset

### ISSUE THREAD

**Issue by arahmanocal** [tsc2017/Frechet-Inception-Distance#2]
How can I implement fid.py for mnist dataset. What I need to change is in fid.py. Can you help me? Thanks so much!

**Comment by tsc2017** [comment]
Hi. Since the Inception network used for calculating FID is pretrained on the ImageNet dataset, it makes no sense to use it on datasets that are too different from ImageNet (_e.g._,  a dataset of hand-written digits or a dataset that contains images of objects from a single category). 

Still, you can train a classifier specialized for MNIST and use its activations to compute the "Fréchet Classifier Distance", as is noted in `README.MD`.
