### ISSUE TITLE
FID between a dataset and a single sample

### ISSUE THREAD

**Issue by caesar-one** [tsc2017/Frechet-Inception-Distance#6]
is there a way to calculate the Frechet Inception Distance between a dataset and just one sample (instead of a set of them), producing consistent results?

**Comment by tsc2017** [comment]
Sorry, I didn't notice this issue until just now. 
If there is only one sample, the estimator of the covariance matrix is always O and has very high variance.

Still, one can compute the FID. With my API, you can duplicate the single sample so that the two sets of samples have the same size. But keep in mind that the FID is highly inaccurate if the empirical distribution of the one-sample dataset is very different from the distribution where the single sample comes from.

**Comment by caesar-one** [comment]
Thank you very much for your answer. Finally, I solved calculating the distribution for one set, then I used mean and co-variance matrix to compute the likelihood of my sample's features given the distribution.
